services:
  # The "Thin" S3 API
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - S3_BUCKET=test-bucket
      - S3_ENDPOINT_URL=http://localstack:4566
      - REDIS_URL=redis://redis:6379
      - DEBUG=true
    depends_on:
      - redis
      - localstack
    volumes:
      - .:/app
    networks:
      - thin-s3-network

  # Background Worker for processing tasks
  worker:
      build: .
      command: python -m app.worker.tasks
      depends_on:
        - redis
        - localstack
      environment:
        - REDIS_URL=redis://redis:6379/0
        - S3_ENDPOINT_URL=http://localstack:4566
      networks:
        - thin-s3-network

  # Redis for metadata & TTL tracking
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --notify-keyspace-events Ex
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - thin-s3-network

  # LocalStack for local S3 simulation
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PERSISTENCE=1
      - CLEAN_ON_EXIT=false
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - S3_SKIP_SIGNATURE_VALIDATION=true
    volumes:
      - localstack-data:/var/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - thin-s3-network

networks:
  thin-s3-network:
    driver: bridge

volumes:
  localstack-data:
